interpretator/src/main/kotlin/org/jb/cce/Interpretator.kt, interpretator/src/main/kotlin/org/jb/cce/Session.kt, interpretator/src/main/kotlin/org/jb/cce/actions/ActionSerializer.kt, interpretator/src/main/kotlin/org/jb/cce/actions/Actions.kt, interpretator/src/main/kotlin/org/jb/cce/visitors/CallCompletionsVisitor.kt
=> Token type added to session

completion-plugin/src/main/kotlin/org/jb/cce/actions/EvaluateCompletionForSelectedFilesAction.kt, completion-plugin/src/main/kotlin/org/jb/cce/interpretator/CompletionInvokerImpl.kt
=> Logging actions added

interpretator/src/main/kotlin/org/jb/cce/Interpretator.kt, interpretator/src/main/kotlin/org/jb/cce/actions/ActionSerializer.kt, interpretator/src/main/kotlin/org/jb/cce/actions/Actions.kt
=> call completion action as data class

babelfish-converter/src/main/kotlin/org/jb/cce/BabelFishConverter.kt, babelfish-converter/src/main/kotlin/org/jb/cce/Language.kt, completion-plugin/src/main/kotlin/org/jb/cce/actions/CompletionSettingsDialogWrapper.kt, completion-plugin/src/main/kotlin/org/jb/cce/actions/EvaluateCompletionForSelectedFilesAction.kt, interpretator/src/main/kotlin/org/jb/cce/Interpreter.kt, metrics-evaluator/src/main/kotlin/org/jb/cce/metrics/MetricsEvaluator.kt
=> Multiple languages support in plugin

completion-plugin/src/main/kotlin/org/jb/cce/actions/EvaluateCompletionForSelectedFilesAction.kt, report-generators/src/main/kotlin/org/jb/cce/HtmlReportGenerator.kt
=> generate actions in background

babelfish-converter/src/main/kotlin/org/jb/cce/BabelFishJavaVisitor.kt, babelfish-converter/src/main/kotlin/org/jb/cce/BabelFishUnifiedVisitor.kt, uast/src/main/kotlin/org/jb/cce/uast/statements/declarations/ClassDeclarationNode.kt, uast/src/main/kotlin/org/jb/cce/uast/statements/declarations/MethodDeclarationNode.kt, uast/src/main/kotlin/org/jb/cce/uast/statements/declarations/MethodHeaderNode.kt, uast/src/main/kotlin/org/jb/cce/uast/statements/expressions/references/ReferenceNode.kt
=> uast fixes

completion-plugin/src/main/resources/META-INF/plugin.xml
=> plugin-xml

completion-plugin/src/main/kotlin/org/jb/cce/interpretator/CompletionInvokerImpl.kt, completion-plugin/src/main/kotlin/org/jb/cce/interpretator/DelegationCompletionInvoker.kt, interpretator/src/main/kotlin/org/jb/cce/CompletionInvoker.kt, interpretator/src/main/kotlin/org/jb/cce/Interpreter.kt, interpretator/src/main/kotlin/org/jb/cce/actions/ActionSerializer.kt, interpretator/src/main/kotlin/org/jb/cce/actions/Actions.kt, interpretator/src/main/kotlin/org/jb/cce/visitors/CallCompletionsVisitor.kt
=> Lookup selection

completion-plugin/src/main/kotlin/org/jb/cce/actions/CompletionSettingsDialog.kt, completion-plugin/src/main/kotlin/org/jb/cce/actions/EvaluateCompletionForSelectedFilesAction.kt, completion-plugin/src/main/kotlin/org/jb/cce/interpretator/CompletionInvokerImpl.kt, completion-plugin/src/main/kotlin/org/jb/cce/interpretator/DelegationCompletionInvoker.kt, interpretator/src/main/kotlin/org/jb/cce/CompletionInvoker.kt, interpretator/src/main/kotlin/org/jb/cce/Interpreter.kt, interpretator/src/main/kotlin/org/jb/cce/Lookup.kt, interpretator/src/main/kotlin/org/jb/cce/Suggest.kt, interpretator/src/main/kotlin/org/jb/cce/actions/CompletionStrategy.kt, metrics-evaluator/src/main/kotlin/org/jb/cce/metrics/ESavedMetric.kt, metrics-evaluator/src/main/kotlin/org/jb/cce/metrics/MeanReciprocalRankMetric.kt, metrics-evaluator/src/main/kotlin/org/jb/cce/metrics/PrecisionMetric.kt, metrics-evaluator/src/main/kotlin/org/jb/cce/metrics/RecallMetric.kt, report-generators/src/main/kotlin/org/jb/cce/EvaluationInfo.kt, report-generators/src/main/kotlin/org/jb/cce/FileEvaluationInfo.kt, report-generators/src/main/kotlin/org/jb/cce/HtmlReportGenerator.kt, report-generators/src/main/kotlin/org/jb/cce/SessionSerializer.kt, report-generators/src/main/kotlin/org/jb/cce/info/EvaluationInfo.kt, report-generators/src/main/kotlin/org/jb/cce/info/FileErrorInfo.kt, report-generators/src/main/kotlin/org/jb/cce/info/FileEvaluationInfo.kt, report-generators/src/main/kotlin/org/jb/cce/info/MetricsEvaluationInfo.kt, report-generators/src/main/kotlin/org/jb/cce/info/SessionsEvaluationInfo.kt, report-generators/src/main/resources/script.js
=> ML completion support and some other enhancements

completion-plugin/build.gradle, completion-plugin/src/main/kotlin/org/jb/cce/actions/EvaluateCompletionForSelectedFilesAction.kt, completion-plugin/src/main/kotlin/org/jb/cce/util/DirectoryWatcher.kt, completion-plugin/src/main/resources/META-INF/plugin.xml, interpretator/src/main/kotlin/org/jb/cce/Interpreter.kt, report-generators/src/main/kotlin/org/jb/cce/HtmlReportGenerator.kt, report-generators/src/main/kotlin/org/jb/cce/SessionSerializer.kt
=> Save stat collector logs

README.md, completion-plugin/build.gradle, completion-plugin/src/main/resources/META-INF/plugin.xml, updatePlugins.xml
=> Custom plugin repository

completion-plugin/src/main/kotlin/org/jb/cce/CompletionEvaluator.kt, completion-plugin/src/main/kotlin/org/jb/cce/actions/CompletionEvaluationStarter.kt, completion-plugin/src/main/kotlin/org/jb/cce/actions/CompletionSettingsDialog.kt, completion-plugin/src/main/kotlin/org/jb/cce/actions/EvaluateCompletionForSelectedFilesAction.kt, completion-plugin/src/main/kotlin/org/jb/cce/util/Config.kt, completion-plugin/src/main/kotlin/org/jb/cce/util/ConfigFactory.kt, completion-plugin/src/main/resources/META-INF/plugin.xml, interpretator/src/main/kotlin/org/jb/cce/Interpreter.kt
=> Small enhancements

completion-plugin/src/main/kotlin/org/jb/cce/CompletionEvaluator.kt, completion-plugin/src/main/kotlin/org/jb/cce/actions/CompletionSettingsDialog.kt, completion-plugin/src/main/kotlin/org/jb/cce/util/ConfigFactory.kt, interpretator/src/main/kotlin/org/jb/cce/actions/CompletionPrefixCreator.kt, interpretator/src/main/kotlin/org/jb/cce/actions/CompletionStrategy.kt, interpretator/src/main/kotlin/org/jb/cce/visitors/CallCompletionsVisitor.kt
=> Add settings: no complete previous

completion-plugin/src/main/kotlin/org/jb/cce/CompletionEvaluator.kt, completion-plugin/src/main/kotlin/org/jb/cce/actions/CompletionEvaluationStarter.kt, completion-plugin/src/main/kotlin/org/jb/cce/actions/CompletionSettingsDialog.kt, completion-plugin/src/main/kotlin/org/jb/cce/actions/EvaluateCompletionForSelectedFilesAction.kt, completion-plugin/src/main/kotlin/org/jb/cce/psi/PsiConverter.kt, completion-plugin/src/main/kotlin/org/jb/cce/util/Config.kt, completion-plugin/src/main/kotlin/org/jb/cce/util/ConfigFactory.kt, completion-plugin/src/main/kotlin/org/jb/cce/util/DirectoryWatcher.kt, completion-plugin/testData/java/LambdaInvocationInPlace.java, completion-plugin/testData/java/outs/LambdaInvocationInPlace.out, interpretator/src/main/kotlin/org/jb/cce/Interpreter.kt, interpretator/src/main/kotlin/org/jb/cce/actions/ActionStat.kt, uast/src/main/kotlin/org/jb/cce/uast/statements/expressions/references/MethodCallNode.kt, uast/src/main/kotlin/org/jb/cce/uast/statements/expressions/references/ReferenceNode.kt
=> Actions interpetation enhancements

completion-plugin/build.gradle, completion-plugin/src/main/kotlin/org/jb/cce/UastBuilder.kt, completion-plugin/src/main/kotlin/org/jb/cce/psi/PsiBashVisitor.kt, completion-plugin/src/main/kotlin/org/jb/cce/psi/PsiConverter.kt, completion-plugin/src/main/kotlin/org/jb/cce/psi/PsiPythonVisitor.kt, completion-plugin/src/main/kotlin/org/jb/cce/psi/PsiVisitor.kt, completion-plugin/src/main/resources/META-INF/plugin.xml, completion-plugin/testData/bash/case_statement.sh, completion-plugin/testData/bash/command.sh, completion-plugin/testData/bash/for_loop.sh, completion-plugin/testData/bash/function.sh, completion-plugin/testData/bash/if_statement.sh, completion-plugin/testData/bash/outs/case_statement.out, completion-plugin/testData/bash/outs/command.out, completion-plugin/testData/bash/outs/for_loop.out, completion-plugin/testData/bash/outs/function.out, completion-plugin/testData/bash/outs/if_statement.out, completion-plugin/testData/bash/outs/while_loop.out, completion-plugin/testData/bash/while_loop.sh, interpretator/src/main/kotlin/org/jb/cce/Interpreter.kt, report-generators/src/main/kotlin/org/jb/cce/HtmlReportGenerator.kt, uast/src/main/kotlin/org/jb/cce/uast/Language.kt
=> Bash support

completion-plugin/src/main/kotlin/org/jb/cce/interpretator/DelegationCompletionInvoker.kt, completion-plugin/src/main/kotlin/org/jb/cce/util/ListSizeRestriction.kt
=> Increase waiting time for decreasing number of application listeners

report-generators/resources/options.css, report-generators/src/org/jb/cce/HtmlReportGenerator.kt
Add "Metrics visibility" dropdown checkbox list
Add "Redraw table" button
resolve #116
=> Make metrics table layout customizable

completion-plugin/build.gradle, completion-plugin/src/org/jb/cce/actions/CompletionEvaluationStarter.kt
=> Relative paths support in config.json

report-generators/resources/error.js, report-generators/src/org/jb/cce/HtmlReportGenerator.kt
Fix stacktrace formatting in file reports
Add "Copy to Clipboard" button for stacktrace in file report
resolve #131
=> #131 stacktrace formatting

report-generators/src/org/jb/cce/HtmlReportGenerator.kt
Pagination prevents rendering problems with large html-reports
Search functionality as a bonus
resolve #137
=> Add pagination and search

completion-plugin/src/org/jb/cce/CompletionEvaluator.kt, completion-plugin/src/org/jb/cce/interpretator/CompletionInvokerImpl.kt, completion-plugin/src/org/jb/cce/interpretator/DelegationCompletionInvoker.kt, completion-plugin/src/org/jb/cce/psi/PsiConverter.kt
=> Run read actions only when indexing finished

report-generators/resources/options.css, report-generators/src/org/jb/cce/HtmlReportGenerator.kt
=> #112 freeze summury row

completion-plugin/src/org/jb/cce/CompletionEvaluator.kt, completion-plugin/src/org/jb/cce/actions/CompletionEvaluationStarter.kt, completion-plugin/src/org/jb/cce/actions/EvaluateCompletionForSelectedFilesAction.kt, completion-plugin/src/org/jb/cce/actions/EvaluateCompletionHereAction.kt, completion-plugin/src/org/jb/cce/psi/PsiConverter.kt, completion-plugin/src/org/jb/cce/util/FilesHelper.kt, interpretator/src/org/jb/cce/Interpreter.kt, report-generators/src/org/jb/cce/FileErrorsStorage.kt, report-generators/src/org/jb/cce/HtmlReportGenerator.kt, report-generators/src/org/jb/cce/SessionsStorage.kt
=> Using relative paths

report-generators/src/org/jb/cce/HtmlReportGenerator.kt
=> Fix sorting of metrics columns values

metrics-evaluator/src/org/jb/cce/metrics/AverageSelectedPositionMetric.kt, metrics-evaluator/src/org/jb/cce/metrics/ESavedMetric.kt, metrics-evaluator/src/org/jb/cce/metrics/LatencyMetrics.kt, metrics-evaluator/src/org/jb/cce/metrics/Metric.kt, metrics-evaluator/src/org/jb/cce/metrics/MetricInfo.kt, metrics-evaluator/src/org/jb/cce/metrics/MetricsEvaluator.kt, metrics-evaluator/src/org/jb/cce/metrics/PrecisionMetric.kt, metrics-evaluator/src/org/jb/cce/metrics/RecallMetric.kt, metrics-evaluator/src/org/jb/cce/metrics/SessionsCountMetric.kt, report-generators/src/org/jb/cce/HtmlReportGenerator.kt
Add custom formatting option for metrics
Change numerical data table alignment
Rename `Average Selected Position` to `Mean Rank`
resolve #149
=> Metric formatting

completion-plugin/src/org/jb/cce/CompletionEvaluator.kt, completion-plugin/src/org/jb/cce/interpretator/CompletionInvokerImpl.kt, completion-plugin/src/org/jb/cce/interpretator/DelegationCompletionInvoker.kt, interpretator/build.gradle, interpretator/src/org/jb/cce/CompletionInvoker.kt, interpretator/src/org/jb/cce/FileTextUtil.kt, interpretator/src/org/jb/cce/Interpreter.kt, interpretator/src/org/jb/cce/actions/ActionsGenerator.kt, interpretator/src/org/jb/cce/visitors/CallCompletionsVisitor.kt, report-generators/src/org/jb/cce/HtmlReportGenerator.kt
Evaluations are consistent now.
=> Using testing mode for completion handler

completion-plugin/src/org/jb/cce/util/DirectoryWatcher.kt
=> BufferedReader for logs

build.gradle, report-generators/build.gradle, report-generators/resources/options.css, report-generators/src/org/jb/cce/HtmlReportGenerator.kt
=> kotlinx.html

completion-plugin/src/org/jb/cce/highlighter/Highlighter.kt, report-generators/resources/script.js, report-generators/resources/style.css, report-generators/src/org/jb/cce/HtmlReportGenerator.kt, report-generators/src/org/jb/cce/ReportColors.kt
=> Switch between prefix length in html

metrics-evaluator/src/org/jb/cce/metrics/AverageSelectedPositionMetric.kt, metrics-evaluator/src/org/jb/cce/metrics/ESavedMetric.kt, metrics-evaluator/src/org/jb/cce/metrics/LatencyMetrics.kt, metrics-evaluator/src/org/jb/cce/metrics/MeanRankMetric.kt, metrics-evaluator/src/org/jb/cce/metrics/Metric.kt, metrics-evaluator/src/org/jb/cce/metrics/MetricInfo.kt, metrics-evaluator/src/org/jb/cce/metrics/MetricValueType.kt, metrics-evaluator/src/org/jb/cce/metrics/MetricsEvaluator.kt, metrics-evaluator/src/org/jb/cce/metrics/PrecisionMetric.kt, metrics-evaluator/src/org/jb/cce/metrics/RecallMetric.kt, metrics-evaluator/src/org/jb/cce/metrics/SessionsCountMetric.kt, report-generators/src/org/jb/cce/HtmlReportGenerator.kt
Enhance metrics table formatting and add diff column to reports with 2 evaluation types
resolve #161
=> Diff column

report-generators/resources/options.css, report-generators/src/org/jb/cce/HtmlReportGenerator.kt
=> Diff columns visibility

README.md, completion-plugin/src/org/jb/cce/dialog/EvaluateHereSettingsDialog.kt, completion-plugin/src/org/jb/cce/dialog/FilteringOnInterpretationConfigurable.kt, completion-plugin/src/org/jb/cce/dialog/FiltersConfigurable.kt, completion-plugin/src/org/jb/cce/dialog/FullSettingsDialog.kt, completion-plugin/src/org/jb/cce/evaluation/ActionsInterpretationHandler.kt, completion-plugin/src/org/jb/cce/evaluation/RandomInterpretFilter.kt, interpretator/src/org/jb/cce/InterpretFilter.kt, interpretator/src/org/jb/cce/Interpreter.kt, workspace/src/org/jb/cce/Config.kt, workspace/src/org/jb/cce/ConfigFactory.kt
=> Random locations evaluation

metrics-evaluator/src/org/jb/cce/metrics/MetricInfo.kt, report-generators/src/org/jb/cce/HtmlReportGenerator.kt
=> Empty reports bug

completion-plugin/src/org/jb/cce/actions/BuildMultipleEvaluationsConfig.kt, completion-plugin/src/org/jb/cce/actions/CompletionEvaluationStarter.kt, completion-plugin/src/org/jb/cce/actions/GenerateReportAction.kt, completion-plugin/src/org/jb/cce/dialog/OpenBrowserDialog.kt, completion-plugin/src/org/jb/cce/evaluation/BackgroundStepFactory.kt, completion-plugin/src/org/jb/cce/evaluation/FilteredSessionsStorage.kt, completion-plugin/src/org/jb/cce/evaluation/step/FinishEvaluationStep.kt, completion-plugin/src/org/jb/cce/evaluation/step/HeadlessFinishEvaluationStep.kt, completion-plugin/src/org/jb/cce/evaluation/step/ReportGenerationStep.kt, completion-plugin/src/org/jb/cce/evaluation/step/UIFinishEvaluationStep.kt, report-generators/src/org/jb/cce/HtmlReportGenerator.kt, uast/src/org/jb/cce/uast/NodeProperties.kt, workspace/src/org/jb/cce/Config.kt, workspace/src/org/jb/cce/ConfigFactory.kt, workspace/src/org/jb/cce/SessionsFilter.kt, workspace/src/org/jb/cce/storages/SessionsStorage.kt
=> Filter sessions on report generation step

workspace/src/org/jb/cce/SessionSerializer.kt
=> Fix bug with generic items in html
